# Generated by Django 3.2.18 on 2023-02-23 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=200)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('9.00am', '9.00am'), ('9.30am', '9.30am'), ('10.00am', '10.00am'), ('10.30am', '10.30am'), ('11.00am', '11.00am'), ('11.30am', '11.30am'), ('12.00am', '12.00am')], default='11.00am', max_length=10)),
                ('time_of_booking', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
