# Generated by Django 3.2.18 on 2023-02-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='Booking',
        ),
    ]
